### ISSUE TITLE
Fix check() preventing API key from generating on startup

### ISSUE THREAD

**Issue by aungyin** [themeteorchef/writing-an-api#1]
I clone this recipe to my localhost and try to play around with it.

When I press REFRESH button in api-key page, 

an alert is being shown like "Are you sure? This will invalidate your current Key!",
I pressed OK afterward. 

I suppose new API key should be generated and display on label. But it doesn't.
Is my expectation wrong or other reason exists?

More over, at the first sight to api-key page, 
random API key was not being generated.

**Comment by themeteorchef** [comment]
Hey @aungyin! This is fixed now. The bug was that the call to `check( userId, ... )` inside of the `initApiKey` method was blocking the insert when creating the default user. This happened because the check was looking for a currently logged in user which didn't exist (the user existed in the database but wasn't logged in). 

I've updated the code and article. If you have any questions, let me know!
